# Generated by Django 4.1.1 on 2022-10-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sfechahora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud_servicios.clientes')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud_servicios.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='cobros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cfechahora', models.DateTimeField(auto_now_add=True)),
                ('valorcobrado', models.IntegerField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud_servicios.solicitud')),
            ],
        ),
    ]
