# Generated by Django 4.1.1 on 2022-10-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_servicios', '0002_alter_servicios_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='sfechahora',
            field=models.DateField(auto_now_add=True),
        ),
    ]
